name: Deploy to Hosting
on:
  push:
    branches:
      - main
      - sprint-6/step-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Build
        env: 
            CI: false
        run: |
              npm i
              npm run test-deploy
              npm run build
              cd build

      - name: Deploy to Hosting
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: public_html/space.burger.nomoredomainswork.ru/
          dangerous-clean-slate: true
